export type ITYPE_CONNECT = 'ONLINE' | 'OFFLINE';

export type ILOAI_TRANG_THAI = 'ACTIVE' | 'INACTIVE';

export type ILOAI_KHU_VUC = 'MIEN_BAC' | 'MIEN_NAM' | 'MIEN_TRUNG';

export type ILOAI_MAN_HINH = 'TRANG_CHU' | 'TIN_TUC' | 'DOI_DIEM';

export type ILOAI_CAU_HOI = 'VIETNAMOBILE' | 'SIM' | 'MUA_HANG' | 'GIAO_HANG' | 'THANH_TOAN' | 'XU_LY_SU_CO';

export type ITRANG_THAI = 'ACTIVE' | 'INACTIVE' | 'LOCK';

export type ILOAI_TRANSACTION = 'NEW' | 'APPROVED' | 'REJECTED' | 'CANCELLED';

export type ICUSTOMER_TYPE = 'CORPORATE' | 'INDIVIDUAL';

export type IHAS_CONTRACT = 'TRUE' | 'FALSE';

export type IGENDER = 'MALE' | 'FEMALE';

export type INATIONALTYPE = 'IDCARD' | 'PASSPORT';